name: Docker Build and Push

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository (optional)
        uses: actions/checkout@v3

      - name: Clone Pleroma repository
        run: |
          git clone https://git.pleroma.social/pleroma/pleroma.git pleroma
          cd pleroma

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER_NAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./pleroma  # 使用克隆的 Pleroma 代码作为构建上下文
          push: true
          tags: jkjoy/pleroma:latest
          build-args: |
            ELIXIR_VER=1.14.5
            ERLANG_VER=25.3.2.14
            ALPINE_VER=3.17.9
